### ISSUE TITLE
Error during migrate in ubuntu 15.04

### ISSUE THREAD

**Issue by atuljain** [unicef/rhizome#32]
/home/atul/djangosql/local/lib/python2.7/site-packages/decorator_include/__init__.py:8: RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.
  from django.utils.importlib import import_module

/home/atul/djangosql/local/lib/python2.7/site-packages/tastypie/cache.py:62: RemovedInDjango19Warning: 'get_cache' is deprecated in favor of 'caches'.
  self.cache = get_cache(cache_name)

Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/atul/djangosql/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/home/atul/djangosql/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/atul/djangosql/local/lib/python2.7/site-packages/django/core/management/base.py", line 393, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/atul/djangosql/local/lib/python2.7/site-packages/django/core/management/base.py", line 444, in execute
    output = self.handle(*args, **options)
  File "/home/atul/djangosql/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 93, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/home/atul/djangosql/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 19, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/home/atul/djangosql/local/lib/python2.7/site-packages/django/db/migrations/loader.py", line 47, in __init__
    self.build_graph()
  File "/home/atul/djangosql/local/lib/python2.7/site-packages/django/db/migrations/loader.py", line 176, in build_graph
    self.load_disk()
  File "/home/atul/djangosql/local/lib/python2.7/site-packages/django/db/migrations/loader.py", line 102, in load_disk
    migration_module = import_module("%s.%s" % (module_name, migration_name))
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/media/atul/2735d814-5cc5-423e-9713-f16a39d939e9/mongodata/atulheroku/rhizome/datapoints/migrations/0032_auto_20151129_0605.py", line 10, in <module>
    class Migration(migrations.Migration):
  File "/media/atul/2735d814-5cc5-423e-9713-f16a39d939e9/mongodata/atulheroku/rhizome/datapoints/migrations/0032_auto_20151129_0605.py", line 49, in Migration
    field=simple_history.models.CurrentUserField(related_name='_datapointentry_history', to=settings.AUTH_USER_MODEL, null=True),
AttributeError: 'module' object has no attribute 'CurrentUserField'

**Comment by atuljain** [comment]
STatic file is also not getting called , no css call
